Ci updates
sdelements/bashtester pull request #1
Opened 2018-11-28 22:25 UTC by hrpatel

2018-11-28 22:36 UTC, hrpatel commented
Test

```bash
root@ip-10-100-12-101:/home/ubuntu/bashtester# ./run.sh env 2>/dev/null| grep -E "VERSION|LATEST"
_BASH_VERSION=3.0
_BASH_LATEST_PATCH=22
_BASH_VERSION=3.1
_BASH_LATEST_PATCH=23
_BASH_VERSION=3.2
_BASH_LATEST_PATCH=57
_BASH_VERSION=4.0
_BASH_LATEST_PATCH=44
_BASH_VERSION=4.1
_BASH_LATEST_PATCH=17
_BASH_VERSION=4.2
_BASH_LATEST_PATCH=53
_BASH_VERSION=4.3
_BASH_LATEST_PATCH=48
_BASH_VERSION=4.4
_BASH_LATEST_PATCH=23
_BASH_VERSION=5.0-beta
_BASH_LATEST_PATCH=0
```

2018-11-29 15:07 UTC, hrpatel commented
Added more test results to the README as examples

2018-11-29 15:41 UTC, antevens commented
+1

2018-11-29 16:15 UTC, adamgilbert requested changes
Minor style notes... +1 otherwise.

2018-11-29 16:15 UTC, adamgilbert commented on run.sh
> +    target_bash_version=${version} docker-compose run bash-tester /usr/local/bin/bash -c "${@}"
Should ${version} be in quotes?

2018-11-29 16:15 UTC, adamgilbert commented on run.sh
>      color_echo cyan "Bash tester, tests a bash script/command on all currently supported bash versions"
I think we're doing single quotes on non-interpolated strings.

2018-11-29 16:15 UTC, adamgilbert commented on run.sh
>      color_echo cyan "Typically this would be used as a git submodule and will map it's parent directory as /code"
Same here.

2018-11-29 16:26 UTC, hrpatel commented on run.sh
>      color_echo cyan "Bash tester, tests a bash script/command on all currently supported bash versions"
Done

2018-11-29 16:26 UTC, hrpatel commented on run.sh
>      color_echo cyan "Typically this would be used as a git submodule and will map it's parent directory as /code"
There is a single quote in the line so I'm leaving the outside ones as is

2018-11-29 16:28 UTC, hrpatel commented on run.sh
> +    target_bash_version=${version} docker-compose run bash-tester /usr/local/bin/bash -c "${@}"
Done

2018-11-29 16:37 UTC, adamgilbert approved these changes

2018-11-29 16:38 UTC, adamgilbert commented on run.sh
>      color_echo cyan "Typically this would be used as a git submodule and will map it's parent directory as /code"
Works for me.

2018-11-29 16:40 UTC, merged